### ISSUE TITLE
No library 

### ISSUE THREAD

**Issue by somedude21** [minecraft-linux/mcpelauncher-ui-manifest#32] opened 2021-01-17 06:09 UTC
Signed in with google and chose a compatible version then this happened
Error while extracting the downloaded file(s), please report this error: The specified files are not a valid collection of Minecraft apks, they don't contain libminecraftpe.so Valid Minecraft apk CPU architectures for this pc / launcher are x86_64

**Comment by ChristopherHX** [comment] 2021-01-17 16:42
> chose a compatible version

Which Minecraft Version? (fully qualified like `1.16.201.02 (x86_64)`)
There are so many Minecraft Versions.

Also please provide the Launcher Version, in Settings -> About.
Furthermore you hopefully don't have enabled any Settings of the Dev tab.

**Comment by somedude21** [comment] 2021-01-17 20:50
This project allows you to launch Minecraft: Bedrock Edition (as in the edition w/o the Edition suffix, previously known as Minecraft: Pocket Edition). The launcher supports Linux and OS X.

Version Unknown OpenSource Build (build 0)
© Copyright 2018-2020, MrARM & contributors
tried launching 1.16.201.02 (x86_64)

**Comment by somedude21** [comment] 2021-01-17 21:09
for some reason only 1.14.1.5 Is correctly installing

**Comment by ChristopherHX** [comment] 2021-01-17 21:30
> tried launching 1.16.201.02 (x86_64)

You didn't notice that it would display 1.16.201.0**1** (x86_64)` instead? The version name I proved was only a sample.

I currently cannot reproduce your issue, I just tried to download `1.16.201.01 (x86_64)` and it worked fine for me.
Maybe this error was caused by a internet connection failure?

You have proven to own the game, therefore you can savely import an apk x86_64 of the game.
Possible workaround if retrying fails.
- Get the aurora app store on your android device or emulator
  You can get it here https://auroraoss.com/
- open the sidebar
- press spoof
- press spoof device 
- select an x86_64 device from the list
  like Aspire one 1-431
- logout from your google account
  This step should make shure spoof device will work
- log into your google account
- search minecraft
- press the `...` 3 dot menu
- press manual download
- Enter the versioncode 981620101 this number can be found here https://github.com/minecraft-linux/mcpelauncher-versiondb/blob/283a95d1bf61e83f06ee0eaff9b616fe34e546b2/versions.json#L2471
- press download
- copy the apk('s) might be multiple from `<internal storage>/Aurora/` to your pc
- import all apk('s) and try launching the game

**Comment by ChristopherHX** [comment] 2021-01-17 21:36
> for some reason only 1.14.1.5 Is correctly installing

How?
1.14.1.5 is only available in x86, but you are using the flatpak version which only works with 1.14.60.5 x86_64 and higher

**Comment by ScaredPenguinXXL** [comment] 2021-08-31 13:15
having the same issue on Version 20210813 (The Sonic Master) (build APPIMAGE)
© Copyright 2018-2021, MrARM & contributors.

and another error when retrying

Downloading file failed: Status[405] ''

**Comment by ChristopherHX** [comment] 2021-08-31 13:30
@ScaredPenguinXXL 
Ask the sonic master for support. You are using a piracy version which abuses the source code of this launcher.

Also somedude is not interested in this issue, so I can close it.

**Closed as completed by ChristopherHX** 2021-08-31 13:30 UTC
Labels: bug, help wanted
